CREATE TABLE `majors` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(25) UNIQUE,
  `name` VARCHAR(255) NOT NULL,
  `data` JSON NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);

CREATE TABLE `students` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(25) UNIQUE,
  `name` VARCHAR(255) NOT NULL,
  `data` JSON NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  `attempt` INT NULL,
  `intake` VARCHAR(4) NOT NULL,
  `credit` INT NULL,
  `status` VARCHAR(255) NULL,
  `major_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`major_id`) REFERENCES `majors` (`id`)
);

CREATE TABLE `teachers` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(25) UNIQUE,
  `name` VARCHAR(255) NOT NULL,
  `data` JSON NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE `classes` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(25) UNIQUE,
  `name` VARCHAR(255) NOT NULL,
  `major_id` BIGINT NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `data` JSON NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);

CREATE TABLE `assignments` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `class_id` BIGINT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `verified` BOOL NOT NULL DEFAULT FALSE,
  `data` JSON NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);

CREATE TABLE `reports` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `ref_id` VARCHAR(255) NOT NULL,
  `class_id` BIGINT NOT NULL,
  `assignment_id` BIGINT NOT NULL,
  `student_id` BIGINT NOT NULL,
  `file` MEDIUMBLOB NULL,
  `url` VARCHAR(255) NULL,
  `data` JSON NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);

CREATE TABLE `meetings` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `class_id` BIGINT NOT NULL,
  `student_id` BIGINT NOT NULL,
  `teacher_id` BIGINT NOT NULL,
  `from` DATETIME NOT NULL,
  `to` DATETIME NOT NULL,
  `room` VARCHAR(255) NOT NULL,
  `report_time` VARCHAR(40),
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);

create table settings
(
    `key` VARCHAR(255) NOT NULL,
    `value` TEXT NOT NULL,
    PRIMARY KEY (`key`)
);



